### ISSUE TITLE
bloom release installs files to recursively generated paths

### ISSUE THREAD

**Issue by christianrauch** [ros-infrastructure/bloom#492] opened 2018-10-06 19:24 UTC
I am trying to release a pure CMake package to the ROS2 repo: [apriltag2-0.9.8.zip](https://github.com/ros-infrastructure/bloom/files/2453303/apriltag2-0.9.8.zip)

Its `CMakeLists.txt` installs header files via:
`install(DIRECTORY . DESTINATION ${CMAKE_INSTALL_PREFIX}/include/${PROJECT_NAME}/ )`
which works successfully for a regular call to `cmake` and in a pre-release test.

E.g. a ROS1 pre-release test via:
```bash
mkdir -p /tmp/prerelease_job
cd /tmp/prerelease_job
generate_prerelease_script.py \
  https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml \
  melodic default ubuntu bionic amd64 \
  --custom-repo \
    apriltag__custom-1:git:https://github.com/christianrauch/apriltag2.git:master \
  --level 1 \
  --output-dir ./
```
correctly installs header files to: `/tmp/catkin_workspace/devel_isolated/apriltag/include/apriltag/`. See the full log: [apriltag_prerelease.txt](https://github.com/ros-infrastructure/bloom/files/2453328/apriltag_prerelease.txt)

A release via bloom generates install paths that are recursively generated, e.g.:
`-- Installing: /tmp/binarydeb/ros-bouncy-apriltag-0.9.8/debian/ros-bouncy-apriltag/opt/ros/bouncy/include/apriltag//./debian/ros-bouncy-apriltag/opt/ros/bouncy/include/apriltag/debian/ros-bouncy-apriltag/opt/ros/bouncy/include/apriltag/debian/ros-bouncy-apriltag/opt/ros/bouncy/include/apriltag/debian/ros-bouncy-apriltag/opt/ros/bouncy/include/apriltag/debian/ros-bouncy-apriltag/opt/ros/bouncy/include/apriltag/common/pjpeg.h`
which after some recursions fails.

It appears that the files are recursively installed into a subfolder of the source folder.
See the full release log: 
[apriltag_build1.txt](https://github.com/ros-infrastructure/bloom/files/2453331/apriltag_build1.txt)

**Comment by nuclearsandwich** [comment] 2018-12-10 16:50
This is happening still

```
CMake Error at cmake_install.cmake:77 (file):
  file INSTALL cannot make directory
  "/tmp/binarydeb/ros-crystal-apriltag-0.9.8/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag//./debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/debian/ros-crystal-apriltag/opt/ros/crystal/include/apriltag/obj-x86_64-linux-gnu/CMakeFiles":
  File name too long
```

**Comment by christianrauch** [comment] 2018-12-10 17:14
I removed `${CMAKE_INSTALL_PREFIX}` from the install `DESTINATION` (https://github.com/christianrauch/apriltag2/commit/064c047d699a308022193c339df94cfd0606a5d6) in the hope that this will resolve the issue.
Somehow the header files get installed to a location which is then picked recursively for installation. I am still not sure if the problem is in the CMake or the build server. The CMake file looks valid and build/installs fine on my system locally and the pre-release (see above).

I am unable to reproduce the issue locally on my machine. The only way to see if a bugfix is effective, is for me to push to the official build server. Is there a way to test the real build on a another build server where I could push more frequently to test possible workarounds?

**Comment by dirk-thomas** [comment] 2018-12-10 17:17
The problem is related to this install rule in the `apriltag2` package: https://github.com/christianrauch/apriltag2-release/blob/268ee80676839cc40f992b924f32d5f9d3582d1c/CMakeLists.txt#L34-L38

When the Debian package is being built artifacts are being created in the `debian` subdirectory. The problem is that this install rule also applies to files in that location and therefore recursively keeps installing files.

You should be able to reproduce the problem by trying to create a Debian package locally using the linked branch from the release repo.

**Comment by christianrauch** [comment] 2018-12-10 17:43
Thanks @dirk-thomas. I am now able to reproduce the issue on branch `debian/crystal/bionic/apriltag` of the release repo after changing the `format` (https://github.com/christianrauch/apriltag2-release/blob/debian/crystal/bionic/apriltag/debian/source/format) from `quilt` to `native`.
I am going to release an updated package soon.

**Comment by christianrauch** [comment] 2018-12-11 01:55
I overlooked, and it actually surprises me, that the artefacts for the Debian packages are created inside the source folder. The list of header files is now globed before the install, which should prevent recursive calls during install.

**Comment by dirk-thomas** [comment] 2018-12-11 01:58
If the new build passes please close this ticket.

**Comment by nuclearsandwich** [comment] 2018-12-11 02:17
http://build.ros2.org/job/Cbin_uB64__apriltag__ubuntu_bionic_amd64__binary/2/ :1st_place_medal:

**Closed by nuclearsandwich** 2018-12-11 02:17 UTC
Labels: invalid
