### ISSUE TITLE
jenkins build fail  : dpkg-source: error: syntax error in source/debian/control at line 14: block lacks the 'Package' field

### ISSUE THREAD

**Issue by kintzhao** [ros-infrastructure/bloom#389] opened 2016-05-03 09:01 UTC
I try to release the indigo version of `rplidar_ros`. but jenkins fails, i can not find the reasons.

-----------------------------------------

```
rplidar_ros (indigo) - 1.5.2-0

The packages in the rplidar_ros repository were released into the indigo distro by running /usr/bin/bloom-release rplidar_ros --track indigo --rosdistro indigo on Fri, 29 Apr 2016 13:10:19 -0000

The rplidar_ros package was released.

Version of package(s) in repository rplidar_ros:

upstream repository: https://github.com/robopeak/rplidar_ros.git
release repository: https://github.com/robopeak/rplidar_ros-release.git
rosdistro version: 1.5.3-0
old version: null
new version: 1.5.2-0
Versions of tools used:

bloom version: 0.5.21
catkin_pkg version: 0.2.10
rosdep version: 0.11.4
rosdistro version: 0.4.7
vcstools version: 0.1.38

rplidar_ros-release (hydro) - 1.0.1-0

The packages in the rplidar_ros-release repository were released into the hydro distro by running /usr/bin/bloom-release --rosdistro hydro --track hydro rplidar_ros-release --edit on Mon, 02 Jun 2014 18:23:05 -0000

The rplidar_ros package was released.

Version of package(s) in repository rplidar_ros-release:

rosdistro version: null
old version: null
new version: 1.0.1-0
Versions of tools used:

bloom version: 0.5.9
catkin_pkg version: 0.2.2
rosdep version: 0.10.25
rosdistro version: 0.3.4
vcstools version: 0.1.33
rplidar_ros-release
```

-----------------------------
build fail  email

```
Step 17 : USER buildfarm
---> Using cache
---> d2c3c1628ba1
Step 18 : ENTRYPOINT sh -c
---> Using cache
---> 68db8455ea9d
Step 19 : CMD PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/release/get_sources.py --rosdistro-index-url https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml indigo rplidar_ros ubuntu trusty --source-dir /tmp/sourcedeb/source && PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/release/build_sourcedeb.py --source-dir /tmp/sourcedeb/source
---> Using cache
---> 6b229ccbcf05
Successfully built 6b229ccbcf05
+ echo # END SECTION
# END SECTION
+ echo # BEGIN SECTION: Run Dockerfile - generate sourcedeb
# BEGIN SECTION: Run Dockerfile - generate sourcedeb
+ rm -fr <http://build.ros.org/job/Isrc_uT__rplidar_ros__ubuntu_trusty__source/ws/sourcedeb>
+ mkdir -p <http://build.ros.org/job/Isrc_uT__rplidar_ros__ubuntu_trusty__source/ws/sourcedeb/source>
+ docker run --rm --cidfile=<http://build.ros.org/job/Isrc_uT__rplidar_ros__ubuntu_trusty__source/ws/docker_sourcedeb/docker.cid> --net=host -v <http://build.ros.org/job/Isrc_uT__rplidar_ros__ubuntu_trusty__source/ws/ros_buildfarm>:/tmp/ros_buildfarm:ro -v <http://build.ros.org/job/Isrc_uT__rplidar_ros__ubuntu_trusty__source/ws/sourcedeb>:/tmp/sourcedeb sourcedeb.indigo_ubuntu_trusty_rplidar_ros
# BEGIN SUBSECTION: get sources
**## Invoking 'git clone --branch debian/ros-indigo-rplidar-ros_1.5.2-0_trusty --depth 1 --no-single-branch https://github.com/robopeak/rplidar_ros-release.git /tmp/sourcedeb/source'**
Cloning into '/tmp/sourcedeb/source'...
Note: checking out 'b24ccdad8ca0fe2d75b3a42c973bd2735bfcdd6f'.
 
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
 
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
 
  git checkout -b new_branch_name
 
Package 'rplidar_ros' version: 1.5.2-0trusty
Package maintainer emails: support@slamtec.com
# END SUBSECTION
# BEGIN SUBSECTION: build sourcedeb
Invoking 'gbp buildpackage --git-ignore-new --git-ignore-branch -S -us -uc --lintian-opts --suppress-tags newer-standards-version' in '/tmp/sourcedeb/source'
gbp:info: ros-indigo-rplidar-ros_1.5.2.orig.tar.gz does not exist, creating from 'release/indigo/rplidar_ros/1.5.2-0'
dpkg-buildpackage -rfakeroot -d -us -uc -i -I -S
dpkg-buildpackage: source package ros-indigo-rplidar-ros
dpkg-buildpackage: source version 1.5.2-0trusty
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by SlamTec_supporter <support@slamtec.com>
dpkg-source -i -I --before-build source
**## dpkg-source: error: syntax error in source/debian/control at line 14: block lacks the 'Package' field
dpkg-buildpackage: error: dpkg-source -i -I --before-build source gave error exit status 255
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -d -us -uc -i -I -S failed
gbp:error: Couldn't run 'debuild -i -I -S -us -uc --lintian-opts --suppress-tags newer-standards-version': debuild -i -I returned 29**
# END SUBSECTION
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/release/build_sourcedeb.py", line 22, in <module>
    sys.exit(main())
  File "/tmp/ros_buildfarm/scripts/release/build_sourcedeb.py", line 18, in main
    return build_sourcedeb(args.source_dir)
  File "/tmp/ros_buildfarm/ros_buildfarm/sourcedeb_job.py", line 99, in build_sourcedeb
    subprocess.check_call(cmd, cwd=sources_dir)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gbp', 'buildpackage', '--git-ignore-new', '--git-ignore-branch', '-S', '-us', '-uc', '--lintian-opts', '--suppress-tags', 'newer-standards-version']' returned non-zero exit status 1
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```

**Comment by wjwwood** [comment] 2016-05-03 17:45
@kintzhao sorry for the delay, I've been meaning to look into your issue. I'll try to do that tonight.

**Comment by kintzhao** [comment] 2016-05-04 03:41
@wjwwood , Now we are down version to 1.5.2.0 from 1.5.3.0, and the new 1.5.2.0(maintainer emai is ros@slamtec.com) is the new version instead of old 1.5.2.0(maintainer email is support@slamtec.com).  but the jenkins  test at the old 1.5.2.0 version.   [rplidar_ros pull request list](https://github.com/ros/rosdistro/pulls?utf8=%E2%9C%93&q=rplidar_ros) .  why  the  new release branch created by bloom-release is old  not new? Do you give me a tutorial about the operation of down version ? could you give me some advises to solve it?

**Comment by kintzhao** [comment] 2016-05-05 05:39
@wjwwood  I add.   the old version is not perfect, we want to cancel it , change it and bloom a new using old version number （because it is related with the sdk version 2.5.2 ) , how can i do it . how can i cancel the jenkins and release new.

**Comment by wjwwood** [comment] 2016-05-05 19:50
@kintzhao sorry for the delay. I'm unable to figure out what you did when releasing that caused the problem.

I released `rplidar_ros` for ROS Jade to see if I could reproduce the problem:

- Release PR:
  - https://github.com/ros/rosdistro/pull/11410
- Source deb job (trusty):
  - http://build.ros.org/job/Jsrc_uT__rplidar_ros__ubuntu_trusty__source/
- Binary job (trusty amd64):
  - http://build.ros.org/job/Jbin_uT64__rplidar_ros__ubuntu_trusty_amd64__binary/

So as you can see it's working.

----

In order to do the release I created a repository in our "gbp" organization:

- https://github.com/ros-gbp/rplidar_ros-release

I did this because I did not have access to your release repository.

**I did not change the upstream repository at all:** https://github.com/robopeak/rplidar_ros

----

This is what **I** did to do the ROS **Jade** release.

I made the releases into that release repository by doing this command:

- `bloom-release -r jade -t jade rplidar_ros`

And I answered the questions it asked me like so:

```
Release repository url [https://github.com/robopeak/rplidar_ros-release.git]: https://github.com/ros-gbp/rplidar_ros-release.git
```

```
Upstream Repository URI:
  <uri>
    Any valid URI. This variable can be templated, for example an svn url
    can be templated as such: "https://svn.foo.com/foo/tags/foo-:{version}"
    where the :{version} token will be replaced with the version for this release.
  [None]: https://github.com/robopeak/rplidar_ros.git
```

Otherwise I used the default answers.

---

**You** should be able to release for **Indigo**.

First, I sent you an invitation to be an administrator on the release repository:

- https://github.com/orgs/ros-gbp/teams/rplidar_ros_team

Once you accept the invitation, you will be able to push and admin the repository. I can move this repository to another organization if you like later.

Once you've accepted the invitation from your email, you can do the **Indigo** release with this command:

- `bloom-release -r indigo -t indigo rplidar_ros --override-release-repository-url https://github.com/ros-gbp/rplidar_ros-release.git`

The `--override-release-repository-url` option will cause the release to be done in the new release repository I created.

Follow the prompts and it will open a pull request for you and we'll check it out.

----

If your Indigo release is still not working, I can do the release for you and we can try to continue to figure out what your issue is with releasing.

**Comment by wjwwood** [comment] 2016-05-05 19:53
I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.

**Closed by wjwwood** 2016-05-05 19:53 UTC

**Comment by kintzhao** [comment] 2016-05-06 05:00
@wjwwood  thank you very much for your help. I check that [jade release file ](https://github.com/ros-gbp/rplidar_ros-release/blob/debian/jade/trusty/rplidar_ros/src/node.cpp) is not same with [upstream file](https://github.com/robopeak/rplidar_ros/blob/master/src/node.cpp) . And i did not delete the upstream TAG1.5.2,  is it the main reason for my last question `the new 1.5.2.0(maintainer emai is ros@slamtec.com) is the new version instead of old 1.5.2.0(maintainer email is support@slamtec.com). but the jenkins test at the old 1.5.2.0 version. rplidar_ros pull request list . why the new release branch created by bloom-release is old not new?`    
----------------------------------------------------
add question:  why my release indigo jenkins jobs fail, and your jade  jenkins jobs passing usng the same old upstream Tag.  I check that [rplidar_ros/debian/control](https://github.com/robopeak/rplidar_ros-release/blob/debian/indigo/trusty/rplidar_ros/debian/control)  and  [rplidar_ros/debian/control](https://github.com/ros-gbp/rplidar_ros-release/blob/debian/jade/trusty/rplidar_ros/debian/control) 。
why my indigo sources/debian/control  create two blank lines  by bloom-release ?. May be the reason of jenkins fail .  
------------------------------------------------------
Next i will delete the rplidar_ros  upstream tag  1.5.2 ,  release a test release in the  https://github.com/ros-gbp/rplidar_ros-release.git  .

**Comment by kintzhao** [comment] 2016-05-06 05:00
@wjwwood  thank you very much for your help. I check that [jade release file ](https://github.com/ros-gbp/rplidar_ros-release/blob/debian/jade/trusty/rplidar_ros/src/node.cpp) is not same with [upstream file](https://github.com/robopeak/rplidar_ros/blob/master/src/node.cpp) . And i did not delete the upstream TAG1.5.2,  is it the main reason for my last question `the new 1.5.2.0(maintainer emai is ros@slamtec.com) is the new version instead of old 1.5.2.0(maintainer email is support@slamtec.com). but the jenkins test at the old 1.5.2.0 version. rplidar_ros pull request list . why the new release branch created by bloom-release is old not new?`    
 
add question:  why my release indigo jenkins jobs fail, and your jade  jenkins jobs passing usng the same old upstream Tag.  I check that [rplidar_ros/debian/control](https://github.com/robopeak/rplidar_ros-release/blob/debian/indigo/trusty/rplidar_ros/debian/control)  and  [rplidar_ros/debian/control](https://github.com/ros-gbp/rplidar_ros-release/blob/debian/jade/trusty/rplidar_ros/debian/control) 。
why my indigo sources/debian/control  create two blank lines  by bloom-release ?. May be the reason of jenkins fail .  
 
Next i will delete the rplidar_ros  upstream tag  1.5.2 ,  release a test release in the  https://github.com/ros-gbp/rplidar_ros-release.git  .

**Comment by kintzhao** [comment] 2016-05-10 13:06
@wjwwood   I have released a new indigo version.  Thanks for your following and checking.  If this can  build pass, i wish that you can re-release jade version or delete it , because i have ever deleted the old tag 1.5.2 and creator a new tag 1.5.2 today.
