### ISSUE TITLE
python-bloom (0.5.20) from packages.ubuntu.com may be removed or upgraded

### ISSUE THREAD

**Issue by matlabbe** [ros-infrastructure/bloom#406] opened 2016-09-28 13:36 UTC
Hi,

Just had some problems (see this [comment](http://answers.ros.org/question/243556/problem-with-jenkins-bloom-release/?comment=244686#post-id-244686), maybe also the problem of this [question](http://answers.ros.org/question/244681/buildfarm-krel_import-package-checksum-error/)) releasing again my package with `bloom-release` because I had the wrong version. I installed `python-bloom` before adding ROS to this computer, so the one of http://packages.ubuntu.com/xenial/python-bloom (`0.5.20` for Ubuntu 16.04 LTS) has been installed instead of the one from http://packages.ros.org/ros/ubuntu (`0.5.22`).

The version from http://packages.ubuntu.com/xenial/python-bloom may be removed/upgraded to make sure people are installing the right one from http://packages.ros.org/ros/ubuntu

cheers

**Comment by tfoote** [comment] 2016-09-28 18:37
As I mentioned in my [answer](http://answers.ros.org/question/244681/buildfarm-krel_import-package-checksum-error/?answer=244705#post-id-244705) to your question I don't think this is related to the bloom version.

**Comment by wjwwood** [comment] 2016-09-28 18:49
Regardless of the root cause of the problem, we cannot control what version is in packages.ubuntu.com. So thanks for reporting the issue (hopefully it will help others searching for related issues), but I'm going to close this as I can't do anything about it.

**Closed by wjwwood** 2016-09-28 18:49 UTC

**Comment by matlabbe** [comment] 2016-09-28 19:02
thx for the explanations! @tfoote I think it is still relevant for this [comment](http://answers.ros.org/question/243556/problem-with-jenkins-bloom-release/?comment=244642#post-id-244642) though:

> When I do bloom-release, no errors, "jessie" is just not processed, only debian "willy", "xenial" and rpm "23", "24". bloom version = 0.5.20
